title: Srd20 Project
source: docs

collections:
  srd:
    output: true
    permalink: /:title
  msrd:
    output: true
    permalink: /:title
  arcana_unearthed:
    output: true
    permalink: /:title
  character_backgrounds:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'special_abilities'
    values:
      layout: 'special-ability'
