title: Srd20 Project

collections:
  arcana_unearthed:
    output: true
    permalink: /:title
  modern_system_reference_document:
    output: true
    permalink: /:title
  system_reference_document:
    output: true
    permalink: /:title
    layout: default

permalink: /:title
