title: Srd20 Project
email: ericabxy@gmail.com
description: An Open Game Content documentation project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srd20.radicalgnu.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ericabxy

theme: minima

defaults:
- scope:
    path: ''
  values:
   layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: special_abilities
  values:
    layout: special-ability

collections:
  artifacts:
    output: true
    permalink: /:collection/:path
  system:
    output: true
    permalink: /:title
    order:
    - BasicRules/Legal.md
    - BasicRules/Basics.md
    - BasicRules/Description.md
    - BasicRules/Races.md
    - BasicRules/ClassesI.md
    - BasicRules/ClassesII.md
    - BasicRules/SkillsI.md
    - BasicRules/SkillsII.md
    - BasicRules/Feats.md
    - BasicRules/Equipment.md
    - BasicRules/CombatI.md
    - BasicRules/CombatII.md
    - BasicRules/AbilitiesandConditions.md
    - BasicRules/NPCClasses.md
    - BasicRules/PrestigeClasses.md
    - Spells/MagicOverview.md
    - Spells/SpellListI.md
    - Spells/SpellListII.md
    - Spells/SpellsA-B.md
    - Spells/SpellsC.md
    - Spells/SpellsD-E.md
    - Spells/SpellsF-G.md
    - Spells/SpellsH-L.md
    - Spells/SpellsM-O.md
    - Spells/SpellsP-R.md
    - Spells/SpellsS.md
    - Spells/SpellsT-Z.md
    - Monsters/MonstersIntro-A.md
    - Monsters/MonstersB-C.md
    - Monsters/MonstersD-De.md
    - Monsters/MonstersDi-Do.md
    - Monsters/MonstersDr-Dw.md
    - Monsters/MonstersE-F.md
    - Monsters/MonstersG.md
    - Monsters/MonstersH-I.md
    - Monsters/MonstersK-L.md
    - Monsters/MonstersM-N.md
    - Monsters/MonstersO-R.md
    - Monsters/MonstersS.md
    - Monsters/MonstersT-Z.md
    - Monsters/MonstersAnimals.md
    - Monsters/MonstersVermin.md
  modern:
    output: true
    permalink: /:title
  arcana_unearthed:
    output: true
    permalink: /:title
  backgrounds:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title
# end of collections
# collections for just-the-docs theme
just_the_docs:
  collections:
    posts:
      name: Posts
    reference:
      name: Reference
    arcana_unearthed:
      name: Arcana Unearthed
# end of collections for just-the-docs theme
