title: Srd20 Project

collections:
  srd:
    output: true
    permalink: /:title
  msrd:
    output: true
    permalink: /:title
  arcana_unearthed:
    output: true
    permalink: /:title
  character_backgrounds:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
