title: Srd20 Project

collections:
  arcana_unearthed:
    output: true
    permalink: /:title
  msrdocs:
    output: true
    permalink: /:title
  srdocs:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
      type: 'srdocs'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'msrdocs'
    values:
      layout: 'default'
