title: Srd20 Project
email: ericabxy@gmail.com
description: An Open Game Content documentation project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srd20.radicalgnu.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ericabxy

theme: minima
plugins:
- jekyll-default-layout
- jekyll-feed
- jekyll-titles-from-headings

defaults:
  - scope:
      path: ''
      type: reference
    values:
      layout: reference

collections:
  reference:
    output: true
    permalink: /:title
  arcana_unearthed:
    output: true
    permalink: /:title
  backgrounds:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title
# end of collections
# collections for just-the-docs theme
just_the_docs:
  collections:
    posts:
      name: Posts
    reference:
      name: Reference
    arcana_unearthed:
      name: Arcana Unearthed
# end of collections for just-the-docs theme
