title: Srd20 Project

collections:
  arcana_unearthed:
    output: true
    permalink: /:title
  msrd:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title
  srd:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
      type: 'arcana_unearthed'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'srd'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'special_abilities'
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'msrd'
    values:
      layout: 'default'
