title: Srd20 Project

plugins:
  - jekyll-spaceship

collections_dir: docs
collections:
  srd:
    output: true
    permalink: /:title
    sort_by: order
  msrd:
    output: true
    permalink: /:title
  arcana_unearthed:
    output: true
    permalink: /:title
  character_backgrounds:
    output: true
    permalink: /:title
  special_abilities:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
      path: ''
      type: 'special_abilities'
    values:
      layout: 'special-ability'
  -
    scope:
      path: ''
      type: 'srd'
    values:
      layout: 'system-reference-document'
  -
    scope:
      path: ''
      type: 'msrd'
    values:
      layout: 'modern-system-reference-document'
  -
    scope:
      path: ''
      type: 'character_backgrounds'
    values:
      layout: 'character-backgrounds'
